;;;; ***********************************************************************
;;;;
;;;; Name:          command.lisp
;;;; Project:       Delectus 2
;;;; Purpose:       command objects 
;;;; Author:        mikel evins
;;;; Copyright:     2017 by mikel evins
;;;;
;;;; ***********************************************************************

(in-package :delectus.command)

;;; =====================================================================
;;; Commands
;;; =====================================================================
;;; Commands encapsulate events generated by the UI that require
;;; interaction with the model. Commands are posted to the document,
;;; which then executes them against the model.

;;; NOTES
;;; how to get the rowid of an insert:
#|
(with-open-database (db (data-path $store))
  (with-transaction db
    (execute-to-list db "insert into contents (\"Title\") values (\"Santa Claus versus the Martians\")")
    (execute-to-list db "select last_insert_rowid()")))
|#


;;; ---------------------------------------------------------------------
;;; command
;;; ---------------------------------------------------------------------
;;; *exported class*
;;; The type of objects that represent Delectus user commands.

(defclass command ()())

;;; ---------------------------------------------------------------------
;;; insert-row-command
;;; ---------------------------------------------------------------------
;;; *exported class*
;;; 

(defclass insert-row-command (command)())

;;; ---------------------------------------------------------------------
;;; undo-insert-row-command
;;; ---------------------------------------------------------------------
;;; *exported class*
;;; 

(defclass undo-insert-row-command (command)())

;;; ---------------------------------------------------------------------
;;; update-row-command
;;; ---------------------------------------------------------------------
;;; *exported class*
;;; 

(defclass update-row-command (command)())

;;; ---------------------------------------------------------------------
;;; undo-update-row-command
;;; ---------------------------------------------------------------------
;;; *exported class*
;;; 

(defclass undo-update-row-command (command)())

;;; ---------------------------------------------------------------------
;;; delete-row-command
;;; ---------------------------------------------------------------------
;;; *exported class*
;;; 

(defclass delete-row-command (command)())

;;; ---------------------------------------------------------------------
;;; undo-delete-row-command
;;; ---------------------------------------------------------------------
;;; *exported class*
;;; 

(defclass undo-delete-row-command (command)())

;;; ---------------------------------------------------------------------
;;; add-column-command
;;; ---------------------------------------------------------------------
;;; *exported class*
;;; 

(defclass add-column-command (command)())

;;; ---------------------------------------------------------------------
;;; undo-add-column-command
;;; ---------------------------------------------------------------------
;;; *exported class*
;;; 

(defclass undo-add-column-command (command)())

;;; ---------------------------------------------------------------------
;;; delete-column-command
;;; ---------------------------------------------------------------------
;;; *exported class*
;;; 

(defclass delete-column-command (command)())

;;; ---------------------------------------------------------------------
;;; undo-delete-column-command
;;; ---------------------------------------------------------------------
;;; *exported class*
;;; 

(defclass undo-delete-column-command (command)())

;;; ---------------------------------------------------------------------
;;; move-column-command
;;; ---------------------------------------------------------------------
;;; *exported class*
;;; 

(defclass move-column-command (command)())

;;; ---------------------------------------------------------------------
;;; undo-move-column-command
;;; ---------------------------------------------------------------------
;;; *exported class*
;;; 

(defclass undo-move-column-command (command)())

