= Delectus 2 Data Formats
mikel evins
:toc:

== Terminology

[cols="1,4",options="header"]
.Terminology used in this manual
|===
| term |  definition
| *column* | A named collection of *fields* with shared attributes from all *items* in a *list*, stored as a column in a SQLite table.
| *identity* |  A unique identification of some object, distinct from all others. Delectus uses identities for *nodes*, *lists*, *ops*, and other objects it works with. It represents an *identity* using the `identity` datatype.
| *field* | A container for a *value* occupying a single *column* of an *item*.
| *item* | An individual, user-created entry in a list, stored as a row in a SQLite table.
| *list* |  A Delectus document containing data organized in rows and columns, one *item* to each row, and one *field* to each column. An item is a collection of fields; a list is a collection of items. Delectus stores each list in its own SQLite file, along with some associated *metadata*.
| *metadata* and *userdata* | *Userdata* is the information that users create and store in Delectus lists. *Metadata* is information that Delectus automatically creates and stores alongside the userdata, in order to support application features. For example, when you add the item "milk" to a shopping list, the text "milk" is *userdata*; the timestamp recorded when you save the item is *metadata*.
| *node* | A Delectus process running on a specific user account on a specific device. Delectus assigns a distinct *identity* to each node, and records the `identity` of the node that writes each *op* in a list file.
| *op* |  A structure in a list file that represents an update to the state of the list. Delectus list data is represented as a time-ordered append-only log of ops.
|===


== Delectus data types

=== Metadata and userdata

Delectus represents *metadata* using SQLite `NULL`, `NUMBER`, and `TEXT values.`

Delectus represents *userdata* using JSON values stored as `TEXT`.

[cols="1,2,5",options="header"]
.Data types in ops and op messages
|===
| type name | Metadata or Userdata |  description
| `Boolean` | userdata |  JSON `true`, `false`, or `null`. `null` is treated as `false`.
| `column` | userdata | A JSON object that defines a column's attributes. See the `<<column-definition>>` definition, below.
| `field` | userdata | A *value* container in a *userdata* column. Fields contain JSON values.
| `identity` | metadata | A globally unique string derived from a v1 UUID, used in Delectus to uniquely identify certain types of objects, including *nodes*, *lists*, *ops*, *columns*, and *items*.
| `metadata` | metadata | A JSON object giving op-specific metadata in addition to the common columns `optype`, `opid`, `origin`, and `timestamp`. See the `<<metadata-definition>>` definition, below.
| `number` | metadata and userdata | Any JSON number.
| `sort-order` | userdata | `null`, `'ASC'`, or `'DESC'`. Specifies whether a column is the list's sort column, and if so, which direction to sort.
| `string` | metadata and userdata | A text string.
| `timestamp` | metadata | An ISO-8601 time string.
| `value` | userdata | JSON `null`, `'boolean'`, `'number'`, or `'string'`. Specifies the types of values the user expects a column to contain.
|===

=== `column` [[column-definition, column]]

A `column` is a JSON object of the following form:

[JSON]
----
{
  id: <identity>,
  name: <string>,
  type: <value>,
  order: <number>,
  title: <boolean>,
  subtitle: <boolean>,
  sort: <sort-order>,
  deleted: <boolean>
}
----

=== `metadata` [[metadata-definition, metadata]]

A `metadata` value is a JSON object of the following form:

[JSON]
----
{
  peer: <identity>,
  file: <identity>,
  name: <string>,
  item: <identity>,
  deleted: <Boolean>,
}
----

`metadata` objects appear in all ops, where they specify attributes of the op in addition to those in the common columns, `optype`, `opid`, `origin`, and `timestamp`.

Each type of op uses only some of the fields of the `metadata` object. Fields that are not used in a given type of op are not present in the metadata object for that op. The fields used by the four types of ops are as follows:

[cols="1,4",options="header"]
.Op `metadata` by optype
|===
| optype |  metadata fields
| `'sync'` | `peer`, `file`
| `'listname'` | `name`
| `'columns'` | _none_
| `'item'` | `item`, `deleted`
|===


== Ops

An *op* is a structure that represents an update to the state of a Delectus list. A Delectus list is represented as an append-only time-ordered log of ops. Each type of op performs a different type of update to a list.

An op is represented in a Delectus file as a row in the `listdata` table. The `listdata` table is structured as a time-ordered log of ops. Delectus only appends to the `listdata` table; it never deletes or overwrites existing data. Updating an existing op therefore means adding a new op that supersedes the old one.

This append-only discipline enables Delectus to safely merge data from concurrently-modified copies of a list without losing any data.

== Op structure

An *op* is a row in the `listdata` table of a Delectus 2 file that records an update to the state of the list. There are four types of ops:


[cols="1,4",options="header"]
.Op types
|===
| optype |  Description
| `'sync'` | Records that Delectus successfully synchronized this copy of a list with another
| `'listname'` | Sets the (user-assigned) name of the list
| `'columns'` | Asserts the state of the list's columns (both userdata and metadata)
| `'item'` | Adds or updates an individual item in the list
|===

The sum total of all operations that may be performed on a Delectus list are just those described by these four ops.

All ops have a common shared structure, plus structure that varies according to op type.

The common shared structure is shown in table 5:

[cols="1,2,4",options="header"]
.Common op structure
|===
| field | permitted values | description
| `optype` | `"sync"`,`"listname"`,`"columns"`,`"item"` | Identifies the type of op.
| `opid` | `_identity_` | Uniquely identifies the op.
| `origin` | `_identity_` | Uniquely identifies the node that created the op.
| `timestamp` | `_timestamp_` | The time that the op was created, as reported by the creating node.
| `metadata` | `_metadata_` | A JSON object that records metadata attributes of the op.  See the `<<metadata-definition>>` definition, above.
|===

In addition to the common structure, the `columns` and `item` ops share a variable number of *userdata* columns, organized as shown in table 6:

[cols="1,2,4",options="header"]
.Op userdata structure
|===
| field | permitted values | description
| `_[identity]_*` | `_column_` or `_value_`  | The value of the column's field
|===

`_[identity]_*` means one or more `identity` strings, one for each userdata column. The `identity` string is assigned when the user creates the column, and is then used both as the unique identifier for the column, and as the label of the column in the SQLite table that contains it.

Delectus uses `identity` strings for columns so that it can guarantee that there will be no collision between user-created columns, even if a user edits the same list on several different machines. If a column on one device has the same `identity` as a column on another, then you may be sure that they are both copies of the same column, and Delectus can synchronize their contents.

The contents of the column's field in a given op depend on whether it's a `columns` op or an `item` op. In a `columns` op, the column contains a `<<column-definition>>` object that defines the column's attributes. In an `item` op, the column contains a `value`.

Because the user can add userdata columns at any time, the number and names of userdata column is not predefined. Delectus creates a new list with the common shared metadata columns, and normally then adds a default userdata column with a unique identity and the name `'Item'`. It then adds a single item to the list with an empy field in the `'Item'` column.

From that point on, the number, names, and contents of the userdata columns are up to the user.

== Tables

== The `delectus` table

The `delectus` table stores data identifying the file, the list, and the Delectus node that created them. It also records the version of the file format used, and it records a `parent` list if it was created by *compacting* an existing list.

[cols="1,2,4",options="header"]
.Structure of the `delectus` table
|===
| column | type | description
| `listid` | `_identity_`  | The unique identity of this list
| `fileid` | `_identity_`  | The unique identity of this list file
| `origin` | `_identity_`  | The unique identity of the Delectus node that created this list file
| `parent` | `_identity_` or `NULL`  | The unique identity of the Delectus list file from which this file was derived by a *compaction*
| `format` | `_TEXT_`  | The version of the Delectus file format in this list file
|===


== The `listdata` table

The `listdata` table contains the log of ops, and therefore the data and metadata of the list.

[cols="1,2,4",options="header"]
.Structure of the `listdata` table
|===
| field | permitted values | description
| `optype` | `"sync"`,`"listname"`,`"columns"`,`"item"` | Identifies the type of op.
| `opid` | `_identity_` | Uniquely identifies the op.
| `origin` | `_identity_` | Uniquely identifies the node that created the op.
| `timestamp` | `_timestamp_` | The time that the op was created, as reported by the creating node.
| `metadata` | `_metadata_` | A JSON object that records metadata attributes of the op.  See the `<<metadata-definition>>` definition, above.
| `_[identity]_*` | `_column_` or `_value_`  | The value of the column's field
|===

The columns `optype`, `opid`, `origin`, `timestamp`, and `metadata` are always the same in every Delectus list file.

The contents of the `metadata` column are always JSON <<metadata-definition>> objects, but the exact contents of the objects depend on the type of each op. See the <<metadata-definition>> definition, above, for details.

The number and contents of the userdata columns, represented by the `_[identity]_*` entry in table 8, vary from one Delectus list file to another, and may change over time as the user adds and updates data in the list.

When the user adds a column to a list, Delectus creates a new SQLite column with a new `identity`, and inserts a `columns` op to record that fact. When a user deletes a column, Delectus adds a new `column` op that records the deletion in the `metadata` for that column (it does not actually delete the column or any existing data in the file).

When Delectus merges the op logs from two different copies of a list, it takes care to create any columns referenced by the ops that it's inserting in both copies of the list, so that both copies end up with the same columns, and the same ops in the same order, containing the same data.
