= Delectus 2 Tables
:toc:

== Ops and the op log

Conceptually, a Delectus list is a named sequence of *items*, each of which contains user-created data in one or more named *columns*. All of the items of a given list have the same columns. Each item stores a value in each column. The values in different columns may be the same or different, and the values in the same column but different items may be the same or different.

Concretely, Delectus stores these objects in the form of rows in a set of tables in a SQLite file. Each row represents an *op*; an *op*--short for "operation"--is a tuple that asserts a change in the state of the list. A Delectus list file is an append-only, time-ordered log of ops. The current state of its data is the combination of the latest values in its ops.

There are four types of op:

. `sync` ops record a successfully synchronization of two Delectus list files.
. `listname` ops define or update the user-assigned name of the list.
. `columns` ops define or update the *userdata* columns of the list.
. `item` ops insert, update, or delete an individual item in the list.

A Delectus file contains one SQLite table for each of these op types. See the <<delectus-table-definitions>> section for a detailed description of each.

== Userdata and metadata

A Delectus list contains two types of data:

. *userdata* is data created and managed by the user.
. *metadata* is data created and managed automatically by Delectus to support application features.

As an example, when you add "milk" to a shopping list in Delectus, the text "milk" is *userdata*; the timestamp that records when you added the item to the list is *metadata*.

Delectus distinguishes the two types of data and stores them in distinct SQLite columns.

The set of metadata columns is predefined, and so are the labels of those columns.

The set of userdata columns, on the other hand, is open-ended, because a user may add a new column at any time.


== Identities

An *identity* is a globally-unique 128-bit number that Delectus uses to uniquely identify Delectus processes and *userdata columns*.

Delectus identities are v4 UUIDs in the form of unsigned 128-bit integers.

Delectus uses an identity in one of two ways:

. as an <<origin-definition>> object, stored in the SQlite `'origin'` column as a BLOB.
. as a <<userdata-column-label-definition>>, converted to a hexadecimal string with the letter "I" prepended.


== Userdata column labels [[userdata-column-label-definition, userdata column label]]

A user may run any number of Delectus processes at the same time, and may add columns in each to different copies of the same list. Delectus has to be able to merge the logs from two or more lists without losing data.

In order to ensure that it can merge arbitrary logs safely, Delectus automatically generates a new, unique column label for each userdata column at the time it's created. This label is a Delectus identity rendered as a string, with the letter "I" prepended. Converting a UUID to a hexadecimal string yields a string that is valid for labeling a SQLite column, except that about sixty precent of the time it will start with a digit. SQLite doesn't allow column labels to start with digits without escaping, so we prepend the letter "I" to ensure the label is usable without gymnastics.

As an example, a typical Delectus `identity` string is `"f3f02b62f35f48c3bd870759f42bed57"`. If using this value as a userdata column label, Delectus renders it as `"If3f02b62f35f48c3bd870759f42bed57"`.

Users normally never see `identity` strings or userdata column labels. Instead of using the SQLite column label, Delectus renders userdata columns using the user-assigned `'name'` attribute of each column.

== Origins [[origin-definition, origin]]

An *origin* is an identity computed for a given Delectus process. Each time Delectus runs it computes a new origin, and it tags each change to a Delectus list with that origin.

The *origin* conceptually identifies the Delectus process that made a set of changes, but cannot in general be used to locate and identify that process. The `origin` value is a random UUID, and there is no guarantee that the process that created it still exists at any particular time in the future.

Fortunately, it's not important to be able to put your finger on the Delectus process that created a given logged edit; it's only important to be able to distinguish that edit globally from all others in an unambiguous way. Per-process `origin` values achieve that goal.

Delectus stores origins as `BLOB` values in the `origin` column of each SQLite table.

NOTE: Storing origins in this way represents a dependence on implementation details of SQLite. SQLite can index BLOB values, but that feature is an extension to the SQL standard and is not generally supported by other databases. If at some point Delectus needs to support storage in other databases then we may have to invent a method of converting origins to a more suitable format for the destination database.

== Timestamps and items

Each time Delectus writes an op, it assigns it a *timestamp*. The timestamp is an integer that counts the number of milliseconds since the *Delectus epoch*, which is defined to be January 1, 2010 GMT.

The timestamp is not globally unique; only locally unique. A different Delectus process can and will assign the same timestamp to different ops. On the other hand, different Delectus processes have different origins; that means that, because the origins are unique, the pair `(timestamp, origin)` _is_ globally unique. Each op in any copy of a Delectus list is therefore uniquely identifiable, which means that op logs from different Delectus files can be safely merged without loss of data.

=== Items

As the previous section explained, each op added to a Delectus list file is unique. A list's *items* are also unique, but in a different way. Although each item is distinct from every other, a given item may be represented by more than one op. That's because after being added to a list, a given item may be updated any number of times. The ops that update it are each unique, but they all refer to the same item.

Delectus therefore requires a way to identify items and all of the unique ops that apply to each one. Solves this problem by assigning a unique-per-process *itemid* to each item at the time it's created. The itemid is an integer that uniquely identifies a given item among all the ops inserted by the current process.

Once again, two or more Delectus processes can and will assign the same itemid to different items, and, once again, the solution is to identify items using the pair `(itemid, origin)`, because each process assigning itemids will have a distinct origin.

=== The current state

The current state of the data in a Delectus list is just the composition of all the latest relevant ops. For `sync`, `listname`, and `columns` ops, this simply means the ops with the latest timestamps. When two or more ops of the same type have the same timestamp, they're sorted by origin, and the one that sorts last is chosen as the current value.

For `item` ops, the process is similar, but a little more complicated, because we need the latest version of each item. In order to get it, we first gather items into groups by `itemid`, and then sort each group by `timestamp` and then `origin`, just as we do with the other ops. The current items in the list are the latest version of each item according to this method.

== SQlite Tables [[delectus-table-definitions, Delectus tables]]

=== 'delectus'

The `delectus` table stores data identifying the file, the list, and the Delectus node that created them. It also records the version of the file format used, and if the new list was created by *compacting* an existing *parent* list, then it records the `identity` of the parent.

[cols="1,2,4",options="header"]
.Structure of the `delectus` table
|===
| column | type | description
| `listid` | `BLOB`  | The unique `identity` of this list, assigned when it was created.
| `fileid` | `BLOB`  | The unique `identity` of this list file, assigned when it was created.
| `parent` | `BLOB`  | The  `identity` of the Delectus list file from which this file was derived by a *compaction*. If `NULL`, it signifies that the file is not a child of another list file.
| `format` | `TEXT`  | The version of the Delectus file format in this list file
| `next_item` | `integer`  | The item number that will be assigned to the next item created in this file.
|===

=== 'listnames'

The `'listnames'` table records `listname` ops, which set the name of the list. The current name of the list is the value of the `name` field of the latest row of the `listnames` table.

[cols="1,2,4",options="header"]
.Structure of the `listnames` table
|===
| field | type | description
| `origin` | `BLOB` | The `identity` of the Delectus process that created this op.
| `timestamp` | `INTEGER` | The time that the op was created, as reported by the creating node.
| `name` | `TEXT` | The new name of the list.
|===

=== 'columns'

The `'columns'` table records `'columns'` ops, which specify the identities and attributes of *userdata* columns.

[cols="1,2,4",options="header"]
.Structure of the `'columns'` table
|===
| field | type | description
| `origin` | `BLOB` | The `identity` of the Delectus process that created this op.
| `timestamp` | `INTEGER` | The time that the op was created, as reported by the creating node.
| `_[label]_+` | `identity` | A `column` object defining the attributes of the column.
|===

The notation `_[label]_+` represents one or more column labels, each of which is an `identity` string. There may be any number of columns, each created by the user, and each with its own _label_. The contents of each column in the `'columns'` table is a JSON object that gives the attributes of the column.

The `'columns'` and `'item'` tables are required to have the same `_[label]_+` columns.

=== 'items'

[cols="1,2,4",options="header"]
.Structure of the `'items'` table
|===
| field | type | description
| `origin` | `BLOB` | The `identity` of the Delectus process that created this op.
| `timestamp` | `INTEGER` | The time that the op was created, as reported by the creating node.
| `item` | `INTEGER` | An `itemid that uniquely identifies the item that this op represents.
| `deleted` | `Boolean` | Whether this item is marked deleted.
| `_[label]_+` | JSON `null`, `Boolean`, `number`, or `string` | A JSON value.
|===

The notation `_[label]_+` represents one or more column labels, each of which is an `identity` string with the letter "I" prepended. There may be any number of columns, each created by the user, and each with its own _label_. The contents of each column in the `'items'` table is a JSON object that gives the value of that column in the item.

The `'columns'` and `'item'` tables are required to have the same `_[label]_+` columns.
