= The Delectus 2 Edit Log
:toc:

This structure and format of the Delectus edit log

== Overview

The Delectus 2 *editlog* is a text file in *jsonl* format--that is, with a single JSON object per line--that serves as a record of all edits made to a given Delectus list. Delectus can serialize a live list file to an editlog, and can read an editlog to create a list file or merge edits from a remote copy of a list.

This document describes the format of the editlog.

== Organization

The editlog consists of a single *header object* followed by zero or more *op objects*.

The *header object* specifies the unique identifier of the list, and its time of creation and last modification.

The *op objects* represents edits, one per object. Each one updates the state of the list. The current state of the list is the cumulative effect of all edits executed in order.

== The header object

The fields of the header object are as follows:

[cols="1,1,1,5",options="header"]
.Header object
|===
| Field | Delectus data | SQLite type | Description
| `*listid*` | `identity` | `TEXT` | The unique ID of the list.
| `*created*` | `timestamp` | `INTEGER`  | The time that the list was created.
| `*modified*` | `timestamp` | `INTEGER`  | The last time that the list was modified.
|===

== Op objects

An *op* is an assertion of change to some discrete aspect of the Delectus list. An *op object* is a JSON object in the editlog that represents an op.

There are four types of ops:

[cols="1,5",options="header"]
.Op types
|===
| Op type | Description
| *listname* | Sets the name of the list.
| *comment* | Sets the list's comment text.
| *columns* | Defines the list's columns and their metadata.
| *item* | Defines the field values of a single list item.
|===

The bulk of the editlog--the file's entire contents after the initial header object, is made up of op objects, one per line. Each op object represents one of the four types of op, and each one asserts a change to the represented list--an *edit*.

All op objects share a common structure:
[cols="1,1,1,5",options="header"]
.Op structure
|===
| Field | Delectus data | SQLite type | Description
| `*target*` | `"listname"`, `"comment"`, `"columns"`, or an identity string | `TEXT` | The op's target--that is, the aspect of the list that the op changes.
| `*origin*` | origin string | `TEXT`  | The `origin` string of the Delectus session that created the op.
| `*revision*`  | integer  | `INTEGER` | The count of prior changes to the target.
| `*order*`  | double float | `REAL` | The order in which the op was added to the editlog.
| `*timestamp*`  | integer  | `INTEGER` |  The time the edit occurred, according to the session that created the op.
| `*data*`  | JSON object | `TEXT` | The new state of the target data.
|===

If the op's type is `"listname"`, `"comment"`,or `"columns"` then the value of the `target` field is just the name of the op type.

If the op is an `"item"` op, though, then the `target` field contains an *identity string* that uniquely identifies the specific list item that it adds or changes.

== Op data

Each edit expresses its change by carrying with it the new data that replaces the previous value of its target. So, for example, a `"listname"` op carries a string in its `data` field that replaces the previous name of the list. A `"commnet"` op carries a string that becomes the new comment text.

The structures of the `data` field in the `"columns"` and `"item"` ops is slightly more complicated.

=== `columns` data

The `"columns"` op carries a definition of the list's columns, and of all defined attributes of each column. This definition is represented as a JSON `columns` object:

[subs=+quotes]
.JSON `columns` object
----
{ _identity_label_ : _column_definition_, ... }
----

The `columns` object is a map from *identity labels* to JSON `column` objects. Each identity label is the unique identifier of a column. Its value, the `column` object, is a JSON object that defines that specific column's attributes.

The `column` object is defined as follows:

[cols="1,1,5",options="header"]
.JSON `column` object
|===
| Field | Representation | Description
| `*label*` | `string` | The column's unique *identity label*.
| `*name*` | `string` | A user-assigned string used in the Delectus UI as the name of the column.
| `*order*` | `double` | The desired order of presentation for the column.
| `*sort*` | `'ASC'`, `'DESC'`, or `null` | Whether this is the sort column, and if so, which direction to sort the list. At most one column at a time may be the sort column. If no sort column is designated then Delectus displays list items in order of their `order` fields.
| `*title*` | `Boolean` | Whether this is the title column. Delectus displays title columns more prominently in the user interface. Exactly one column at a time is the title column of a list. If the user does not designate a title column then Delectus chooses an arbitrary one (generally the column with the least `order` value).
| `*subtitle*` | `Boolean` | Whether this is the subtitle column. Delectus displays the subtitle column less prominently than the title column, but more prominently than other columns in the UI. At most one column at a time is the subtitle column of a list. If no subtitle column is designated then no column is displayed in subtitle style.
| `*deleted*` | `Boolean` | Whether this column is marked deleted.
|===


=== `item` data

The `"item"` op carries the field values of the target item. Each field value belongs to a specific column, identified by the column's identity label.

The `"item"` op also carries a flag that specifies whether the target item has been marked deleted.

The `item` object is defined as follows:

[cols="1,1,5",options="header"]
.JSON `item` object
|===
| Field | Representation | Description
| `*deleted*` | `Boolean` | Whether the item has been marked deleted.
| `_identity_label_` | `JSON value` | The value of the field in the labeled column.
|===

The `item` object contains one entry for each of the list's columns. Each column is identified by its *identity label*. The value of the entry is a JSON value representing the current value of the labeled field of the item.

Each identity label in the `item` object must be equal to one of the labels of the list's columns, as defined by the most recent `columns` op.
