= Delectus 2 Storage in SQLite Files

Delectus 2 stores *lists* in SQLite files, one list per file. This document explains how Delectus organizes and stores list data in SQLite databases.

== Ops

The basic unit of storage in a Delectus 2 file is an *op*. An *op* is both an instruction that asserts a set of data values, and the concrete representation of the data. A Delectus file is basically an append-only log of ops, along with some additional metadata. The Delectus application constructs its view of a list using SQL queries on the op log.

=== Op format

An *op* is a tuple of values organized as follows:

.The *op* data format
|===
|field name: |`optype`  |`opid` |`origin` |`peer` |`item` |`revision` |`deleted` |`name` |`_columnid*_`

| *datatype:*
|`text`
|`opid`
|`opid`
|`opid`
|`opid`
|`integer`
|`boolean`
|`text`
|`columndata`

|*description:*
|The type of op
|The op's unique ID
|The device that created the op
|A known peer device
|An item's unique ID
|The op's revision number
|Whether the data in the op is marked deleted
|The name being asserted
|Column attributes

|===

Not all ops use all  fields. In fact, the only fields used by all ops are `optype`, `opid`, `origin`, and `revision`. All ops use the same data format, though, so that all can be asserted into the same SQLite table.

The *_columnid*_* actually represents multiple *userdata columns*. These are columns created by users to hold their data. There may be any number of such columns in a list, each with its own attributes object and *columnid*.

The name of a userdata column is not literally `"columnid*"``; rather, it's a unique value generated by Delectus for each userdata column, of type `columnid`. Delectus uses this value internally and does not display it; users normally see the value of the column's `name` attribute instead.


.*The `columnid` type
|===
|type name | description

|`columnid`
|A text string of the form `"Cxxxxxxxxxxxxxxxx"`. The characters after the 'C' are the text of a *time-first UUID string*, but with hyphens removed.

Delectus uses this format so that `columnid` values may be used without escaping to label the SQLite columns that represent Delectus columns.

|===


==== Op field types

The data types used in the fields of an op are defined as follows:

.*op* field types
|===
|type name | description

|`text`
|A text string

|`opid`
|A garden-variety UUID string. Delectus uses *time-first UUIDs*.

|`boolean`
|`true` or `false`

|`columndata`
|A JSON string representing a `columndata` object

|===

==== columndata

A `*columndata*` object is a JSON object that represents the attributes of a *userdata column*. The `columndata` object is defined as follows:

.The `*columdata*` object
|===
|attribute | type

|`id`
|`columnid`

|`name`
|`string`

|`order`
|`double`

|`type`
|`boolean`, `number`, or `text`

|`sort`
|`null` or one of the strings `asc` or `desc`

|===

=== The Delectus ops

Delectus defines four types of ops:

. `*listname*` asserts the name of the current list
. `*columns*` asserts the current values of all column attributes
. `*item*` asserts the vaules of all fields of a specified list item
. `*sync*` asserts that a successful *sync* operation was performed

This section describes each of these ops in greater detail.

.The `*listname*` op
|===
|field name: |`optype`  |`opid` |`origin` |`peer` |`item` |`revision` |`deleted` |`name` |`_columnid*_`

| *value:*
|`"listname"`
|`_opid_`
|`_opid_`
|`null`
|`null`
|`_integer_`
|`null`
|`_text_`
|`null`

|*meaning:*
|The type of op
|This op's unique ID
|The device that created it
|_unused_
|_unused_
|This op's revision number
|_unused_
|The list's new name
|_unused_

|===
