;;;; ***********************************************************************
;;;;
;;;; Name:          command.lisp
;;;; Project:       Delectus 2
;;;; Purpose:       command objects 
;;;; Author:        mikel evins
;;;; Copyright:     2017 by mikel evins
;;;;
;;;; ***********************************************************************

(in-package :delectus)

;;; ---------------------------------------------------------------------
;;; command objects
;;; ---------------------------------------------------------------------
;;; commands encapsulate events generated by the UI that require
;;; interaction with the model. commands are posted to the document,
;;; which then executes them against the model.

(defclass command ()())
