;;;; ***********************************************************************
;;;;
;;;; Name:          command.lisp
;;;; Project:       Delectus 2
;;;; Purpose:       command objects 
;;;; Author:        mikel evins
;;;; Copyright:     2017 by mikel evins
;;;;
;;;; ***********************************************************************

(in-package :delectus.command)

;;; =====================================================================
;;; Commands
;;; =====================================================================
;;; Commands encapsulate events generated by the UI that require
;;; interaction with the model. Commands are posted to the document,
;;; which then executes them against the model.

;;; ---------------------------------------------------------------------
;;; command
;;; ---------------------------------------------------------------------
;;; *exported class*
;;; The type of objects that represent Delectus user commands.

(defclass command ()())
