= Delectus SQL Queries

Files in this directory contain SQL statements used by Delectus to query or update the contents of list files. This file describes the purpose of each one.

The glossary below omits the ".tmpl.sql" file extensions from the file names.

== add-userdata-column

Creates a new *userdata column* in the list.

= create-delectus-table

Creates the initial `delectus` table in a new list file.

= create-list_data-table

Creates the initial `list_data` table in a new list file.

= get-latest-columns

Returns the most recent `columns` op in the list file. The result defines the current columns and their attributes.

= get-latest-items

Returns the most recent `item` op for each distinct item ID in the list file. The results are the latest version of each distinct item.

= get-latest-listname

Returns the most recent `listname` op in the list file. The result defines the current name of the list.

= populate-delectus-table

Stores the standard values in the `delectus` table in the list file when it's first created.
